#! /bin/sh

# startup stuff
sxhkd &
fcitx -d &
setxkbmap pl &
fish -c fehbg &
sh ~/.config/polybar/launch.sh
antidot init
picom --experimental-backends --backend glx -b
easyeffects --gapplication-service &

# mouseid=$(xinput | grep G703 | grep pointer | awk -F= '{print $2}' | awk '{print $1}')
# xinput --set-prop $mouseid 'libinput Accel Speed' -.6

xsetroot -cursor_name left_ptr

# setup workspaces
bspc monitor DP-2 -d Media Docs
bspc monitor DP-4 -d Main Web
bspc monitor HDMI-0 -d Chat Dev Extra Tools

# handle monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


bspc config border_width 2
bspc config window_gap 16

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#88c0d0"

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus     true
bspc config pointer_motion_interval 7ms

bspc rule -a '*:feh' state=floating
bspc rule -a '*:mpv' state=floating
bspc rule -a '*:Minecraft' state=floating
# bspc rule -a Zathura state=floating
# bspc rule -a Anki state=floating
bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a gdlauncher state=floating

